### ISSUE TITLE
PinnedDeployment: Support an arbitrary number of versions

### ISSUE THREAD

**Issue by vllry** [zeitgeistlabs/kubernetes-rollout#13]
Version breakdown would still be % based.

# Example AP

```
versions:
  - identifier: <string>
    replicasPercent: <int>
    template: <PodTemplateSpec>
```

replicasPercent must sum to 100.

## Thoughts

* How to handle rounding options? The more versions there are, the more likely rounding matters on small-medium services.
* List or map for identifiers?
* Is it worth maintaining a simpler BlueGreen object that manages the 2-case of PinnedDeployments?
* Is this awkward for a crude deploy tool to manage?
